---
general:
  logging_mode: terminal

system_components:
  gcp: true
  local_mqtt_gateway: false #true
  db: false #true

logging:
  file_log_folder: 'C:\Users\woute\development\logs'
  min_log_level: debug
  log_collection_name: logs

local_mqtt_gateway:
  broker_address: '192.168.1.83' # WIFI home
  #broker_address: '10.42.0.25' # ETH0

mongo_db:
  host_ip: '192.168.1.83'
  #host_ip: '10.42.0.25'
