---
general:
  logging_mode: terminal  # Options: <terminal, file, db, test>

system_components:
  gcp: false
  mqtt_gateway: true
  db: true
  host_monitor: true

logging:
  file_log_folder: 'C:\Users\woute\development\logs'
  min_log_level: debug
  log_collection_name: logs

mqtt_gateway:
  #broker_address: '192.168.1.83' # WIFI home
  #broker_address: '127.0.0.1'
  broker_address: '127.0.0.1'
  #broker_address: '10.42.0.25' # ETH0

mongo_db:
  #host_ip: '127.0.0.1'
  host_ip: '127.0.0.1'
  #host_ip: '10.42.0.25'
