---
general:
  gcp: false
  logging_mode: terminal

logging:
  filename: log.txt

###
from pathlib import Path
from os import path, sep
repo_name = 'ci-util'
dir_structure = path.normpath(Path.cwd()).split(sep)
index_repo_name = dir_structure.index(repo_name)
project_home = Path(*dir_structure[:index_repo_name+1])
conf_file_location = Path.joinpath(project_home, 'configuration.yml')
print(project_home)
print(conf_file_location)
###

