# add docker_hub credentials to github secrets
# get tag info
# build matrix for different arch

name: build_docker

on: [push]
  #push:
  #  branches: master
  #  tags:
  #    - '*.*.*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout commit"
        uses: actions/checkout@v2

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: "Available platforms"
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: "Prepare docker build"
        # DOCKER_PLATFORMS=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/s390x
        run: echo todo

      - name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "build linux/amd64"
        run: |
          DOCKER_REPO="home_automation_framework"
          DOCKER_ACC="dankersw"
          IMG_TAG="test-amd64"
          docker buildx build -t $DOCKER_ACC/$DOCKER_REPO:$IMG_TAG .. --build-arg tag=$IMG_TAG --platform linux/amd64
          docker push $DOCKER_ACC/$DOCKER_REPO:$IMG_TAG

