name: framework_unit_tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Unit tests with unittest
        run:  |
          coverage run -m unittest discover -s tests/ -p 'test_*.py'
          coverage report -m
