name: home_server_tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f home_server/requirements.txt ]; then pip install -r home_server/requirements.txt; fi
      - name: Unit tests with unittest
        run:  |
          python -m unittest discover -s home_server/tests/ -p 'unittest_*.py'
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.inf