name: static_code_analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Stage 1/2 Static code analysis iot_gateway with pytest
      run: |
        echo "Linting of home_automation_framework folder"
        home_dir=$(pwd)
        sub_dirs=("db"  "iot_gateway"  "logging" "host_health" "framework" "utils")
        for sub_dir in ${sub_dirs[*]}; do
          echo "Linting for src/$sub_dir"
          cd "$home_dir/home_automation_framework/$sub_dir" || { echo "cd error, check location"; exit 1; }
          pylint -j 2 --rcfile="$home_dir/.github/workflows/setup.cfg" --output-format=colorized `ls -R | grep .py$ | xargs`
        done
