name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f home_server/requirements.txt ]; then pip install -r home_server/requirements.txt; fi
    - name: Test with pytest
      run: |
        home_dir=$(pwd)
        pwd
        nproc

        echo "Static code analysis iot_gateway"
        cd home_server/src/iot_gateway/
        pylint -j 4 `ls -R | grep .py$ | xargs`
        cd $home_dir
        pwd
        echo "Static code analysis logging"
        cd home_server/src/logging/
        pylint -j 4 `ls -R | grep .py$ | xargs`
        cd $home_dir

#echo "Static code analysis iot_gateway"
#        pwd
#        pylint `ls -R home_server/src/iot_gateway/ | grep .py$ | xargs`

#pylint `ls -R | grep .py$ | xargs`
