name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Test with pytest
      run: |
        echo "Static code analysis logging"
        pwd
        pylint `ls -R home_server/src/logging/ | grep .py$ | xargs`

        echo "Static code analysis iot_gateway"
        pwd
        pylint `ls -R home_server/src/iot_gateway/ | grep .py$ | xargs`

#pylint `ls -R | grep .py$ | xargs`
